name: MC-JS
version: '${project.version}'
main: de.flori.mCJS.MCJS
api-version: '1.21'
author: Flori
load: STARTUP
description: Modern JavaScript plugin system for Minecraft using Rhino Engine
website: https://github.com/LootingVI/MC-JS
commands:
  jsreload:
    description: Reload JS plugins (all or specific)
    usage: /<command> [plugin]
    permission: mcjs.admin
    aliases: [jsr]
  jslist:
    description: List all loaded JS plugins
    usage: /<command>
    permission: mcjs.admin
    aliases: [jsl]
  jsconfig:
    description: View or reload plugin configuration
    usage: /<command> [reload]
    permission: mcjs.admin
    aliases: [jsc]
permissions:
  mcjs.admin:
    description: Allows managing JS plugins
    default: op
  mcjs.use:
    description: Allows using JS plugin features
    default: true