export const apiDocs = [

  {label: 'api.systems.readData', signature: 'api.systems.readData(pluginId, scope, key, fallbackJson)', category: 'Systems', info: 'Read saved JSON. Use global or player:<UUID> for scope. Data is isolated per plugin and survives restarts.'},
  {label: 'api.systems.writeData', signature: 'api.systems.writeData(pluginId, scope, key, json)', category: 'Systems', info: 'Save a JSON string, up to 128 KiB. Blocks handle JSON conversion automatically.'},
  {label: 'api.systems.deleteData', signature: 'api.systems.deleteData(pluginId, scope, key)', category: 'Systems', info: 'Delete one saved value.'},
  {label: 'api.systems.changeNumber', signature: 'api.systems.changeNumber(pluginId, scope, key, amount)', category: 'Systems', info: 'Add to a saved number atomically and return the new value. A missing value starts at zero.'},
  {label: 'api.systems.claimCooldown', signature: 'api.systems.claimCooldown(pluginId, scope, key, seconds)', category: 'Systems', info: 'Return true and save the new cooldown if ready, otherwise false. Cooldowns survive restarts.'},
  {label: 'api.systems.cooldownRemaining', signature: 'api.systems.cooldownRemaining(pluginId, scope, key)', category: 'Systems', info: 'Get the remaining cooldown in seconds, rounded up.'},
  {label: 'api.systems.purchase', signature: 'api.systems.purchase(pluginId, player, currencyKey, cost, item)', category: 'Systems', info: 'Buy an item with saved player currency. Returns ok, funds or space. Runs on the server thread; this currency is local to the plugin, not Vault.'},
  {label: 'api.systems.grantKit', signature: 'api.systems.grantKit(pluginId, player, key, seconds, items)', category: 'Systems', info: 'Grant a list of 1–54 items on the server thread. Returns ok, cooldown or space. Failed grants restore the inventory and keep the reward available.'},
  {label: 'api.systems.createMenu', signature: 'api.systems.createMenu(title, rows)', category: 'Systems', info: 'Create a menu with 1–6 rows. Add button(slot, item, callback), fill(item), onClose(callback), then open(player). Create a new menu for each player. Callbacks receive player and event on the next tick.'},
  {label: 'api.systems.registerEvent', signature: 'api.systems.registerEvent(eventName, observe, callback)', category: 'Systems', info: 'Register an owned Bukkit event. Observations use MONITOR and ignore cancelled events. Do not modify an observation event. Event names are relative to org.bukkit.event.'},
  {label: 'api.systems.eventPlayer', signature: 'api.systems.eventPlayer(event)', category: 'Systems', info: 'Get the player of a player, block, entity or inventory event. Returns null when no player applies, such as a mob death.'},
  {label: 'api.systems.locationToJson', signature: 'api.systems.locationToJson(location)', category: 'Systems', info: 'Serialize world, coordinates, yaw and pitch to JSON.'},
  {label: 'api.systems.locationFromJson', signature: 'api.systems.locationFromJson(json)', category: 'Systems', info: 'Restore a location; returns null when the saved world is unavailable.'},

  {label: 'onEnable', signature: 'function onEnable()', category: 'Lifecycle', info: 'Called when the plugin starts. Register events and commands here.'},
  {label: 'onDisable', signature: 'function onDisable()', category: 'Lifecycle', info: 'Called when the plugin is stopped or the server shuts down.'},
  {label: 'pluginInfo', signature: '{name, version, author, description}', category: 'Lifecycle', info: 'Plugin metadata read from your plugin. Edit it in the block controls above.'},

  {label: 'api', signature: 'api.*', category: 'Globals', info: 'Main MC-JS API object with all sub-APIs (api.player, api.world, api.item, …).'},
  {label: 'server', signature: 'Server', category: 'Globals', info: 'The running Bukkit server (getWorld, getOnlinePlayers, getMotd, executeCommand …).'},
  {label: 'plugin', signature: 'JavaPlugin', category: 'Globals', info: 'The MC-JS plugin instance itself.'},
  {label: 'logger', signature: 'PluginLogger', category: 'Globals', info: 'Server console logger. logout: logger.info("…"), logger.warning("…"), logger.severe("…").'},
  {label: 'scheduler', signature: 'Scheduler', category: 'Globals', info: 'Bukkit scheduler. Use api.runTaskLater/api.runTaskTimer instead where possible.'},
  {label: 'Bukkit', signature: 'Bukkit', category: 'Globals', info: 'The Bukkit server singleton (same methods as server).'},
  {label: 'Player', signature: 'class Player', category: 'Globals', info: 'org.bukkit.entity.Player exposed as a constant.'},
  {label: 'Material', signature: 'class Material', category: 'Globals', info: 'org.bukkit.Material – use Material.DIAMOND or api.getMaterial("DIAMOND").'},
  {label: 'Location', signature: 'class Location', category: 'Globals', info: 'org.bukkit.Location – new Location(world, x, y, z).'},
  {label: 'World', signature: 'class World', category: 'Globals', info: 'org.bukkit.World.'},
  {label: 'GameMode', signature: 'class GameMode', category: 'Globals', info: 'GameMode.SURVIVAL | CREATIVE | ADVENTURE | SPECTATOR.'},
  {label: 'ItemStack', signature: 'class ItemStack', category: 'Globals', info: 'org.bukkit.inventory.ItemStack.'},
  {label: 'Sound', signature: 'class Sound', category: 'Globals', info: 'org.bukkit.Sound – use Sound.ENTITY_PLAYER_LEVELUP.'},
  {label: 'PotionEffectType', signature: 'class PotionEffectType', category: 'Globals', info: 'org.bukkit.potion.PotionEffectType – e.g. SPEED, REGENERATION.'},

  {label: 'event.player.PlayerJoinEvent', signature: 'api.registerEvent("player.PlayerJoinEvent", e => …)', category: 'Events', info: 'When a player joins. event.getPlayer().'},
  {label: 'event.player.PlayerQuitEvent', signature: 'api.registerEvent("player.PlayerQuitEvent", e => …)', category: 'Events', info: 'When a player quits. event.getPlayer().'},
  {label: 'event.player.PlayerRespawnEvent', signature: 'api.registerEvent("player.PlayerRespawnEvent", e => …)', category: 'Events', info: 'When a player respawns. event.getPlayer(), event.getRespawnLocation().'},
  {label: 'event.player.PlayerDeathEvent', signature: 'api.registerEvent("entity.PlayerDeathEvent", e => …)', category: 'Events', info: 'When a player dies. Get player via event.getEntity().'},
  {label: 'event.player.PlayerMoveEvent', signature: 'api.registerEvent("player.PlayerMoveEvent", e => …)', category: 'Events', info: 'When a player moves. event.getPlayer(), event.getTo().'},
  {label: 'event.player.PlayerInteractEvent', signature: 'api.registerEvent("player.PlayerInteractEvent", e => …)', category: 'Events', info: 'When a player interacts (click). event.getPlayer(), event.getAction().'},
  {label: 'event.player.AsyncPlayerChatEvent', signature: 'api.registerEvent("player.AsyncPlayerChatEvent", e => …)', category: 'Events', info: 'When a player chats. event.getPlayer(), event.getMessage(), event.setCancelled().'},
  {label: 'event.player.PlayerBedEnterEvent', signature: 'api.registerEvent("player.PlayerBedEnterEvent", e => …)', category: 'Events', info: 'When a player enters a bed. event.getPlayer().'},
  {label: 'event.block.BlockPlaceEvent', signature: 'api.registerEvent("block.BlockPlaceEvent", e => …)', category: 'Events', info: 'When a block is placed. event.getPlayer(), event.getBlock().'},
  {label: 'event.block.BlockBreakEvent', signature: 'api.registerEvent("block.BlockBreakEvent", e => …)', category: 'Events', info: 'When a block is broken. event.getPlayer(), event.getBlock().'},
  {label: 'event.entity.EntityDamageEvent', signature: 'api.registerEvent("entity.EntityDamageEvent", e => …)', category: 'Events', info: 'When an entity takes damage. event.getEntity(), event.getDamage(), event.setCancelled().'},
  {label: 'event.inventory.InventoryClickEvent', signature: 'api.registerEvent("inventory.InventoryClickEvent", e => …)', category: 'Events', info: 'When a player clicks in an inventory. event.getSlot(), event.getCurrentItem().'},
  {label: 'event.inventory.InventoryCloseEvent', signature: 'api.registerEvent("inventory.InventoryCloseEvent", e => …)', category: 'Events', info: 'When an inventory is closed. event.getInventory().'},

  {label: 'api.broadcast', signature: 'api.broadcast(message, [permission])', category: 'Messages', info: 'Sends a message to all players (optionally only those with a permission). Supports & color codes.'},
  {label: 'api.sendMessage', signature: 'api.sendMessage(sender, message)', category: 'Messages', info: 'Sends a chat message to a player, command sender, or console.'},
  {label: 'api.sendTitle', signature: 'api.sendTitle(player, title, subtitle)', category: 'Messages', info: 'Shows a title/subtitle to a player. Supports & color codes.'},
  {label: 'api.sendTitleWithTimes', signature: 'api.sendTitle(player, title, subtitle, fadeIn, stay, fadeOut)', category: 'Messages', info: 'Title with custom fade-in, stay and fade-out duration in ticks.'},
  {label: 'api.sendActionBar', signature: 'api.sendActionBar(player, message)', category: 'Messages', info: 'Shows a short action-bar message above the player hotbar.'},
  {label: 'api.player.sendMessage', signature: 'api.player.sendMessage(sender, message)', category: 'Messages', info: 'Same as api.sendMessage.'},

  {label: 'api.getPlayer', signature: 'api.getPlayer(name)', category: 'Player', info: 'Returns the online player with the given name or null.'},
  {label: 'api.getPlayerExact', signature: 'api.getPlayerExact(name)', category: 'Player', info: 'Returns the online player with the exact name (case-sensitive) or null.'},
  {label: 'api.getPlayerByUUID', signature: 'api.getPlayerByUUID(uuid)', category: 'Player', info: 'Returns the online player with the given UUID or null.'},
  {label: 'api.getOnlinePlayers', signature: 'api.getOnlinePlayers()', category: 'Player', info: 'Returns all online players as a list.'},
  {label: 'api.getPlayerFromSender', signature: 'api.getPlayerFromSender(sender)', category: 'Player', info: 'Converts a command sender to a player, or null if it is the console.'},
  {label: 'api.kickPlayer', signature: 'api.kickPlayer(player, reason)', category: 'Player', info: 'Kicks a player with a reason.'},
  {label: 'api.player.banPlayer', signature: 'api.player.banPlayer(name, reason)', category: 'Player', info: 'Bans a player by name.'},
  {label: 'api.player.unbanPlayer', signature: 'api.player.unbanPlayer(name)', category: 'Player', info: 'Unbans a player by name.'},
  {label: 'api.player.isBanned', signature: 'api.player.isBanned(name)', category: 'Player', info: 'Checks whether a player is banned.'},
  {label: 'api.player.addToWhitelist', signature: 'api.player.addToWhitelist(name)', category: 'Player', info: 'Adds a player to the whitelist.'},
  {label: 'api.player.removeFromWhitelist', signature: 'api.player.removeFromWhitelist(name)', category: 'Player', info: 'Removes a player from the whitelist.'},
  {label: 'api.player.isWhitelisted', signature: 'api.player.isWhitelisted(name)', category: 'Player', info: 'Checks whether a player is whitelisted.'},
  {label: 'api.player.setWhitelistEnabled', signature: 'api.player.setWhitelistEnabled(enabled)', category: 'Player', info: 'Enables or disables the server whitelist.'},
  {label: 'api.player.setGameMode', signature: 'api.player.setGameMode(player, GameMode.…)', category: 'Player', info: 'Sets the game mode of a player.'},
  {label: 'api.player.getGameMode', signature: 'api.player.getGameMode(player)', category: 'Player', info: 'Returns the game mode of a player.'},
  {label: 'api.player.teleport', signature: 'api.player.teleport(player, location)', category: 'Player', info: 'Teleports a player to a location.'},
  {label: 'api.player.kickPlayer', signature: 'api.player.kickPlayer(player, reason)', category: 'Player', info: 'Kicks a player with a reason.'},
  {label: 'api.player.setHealth', signature: 'api.player.setHealth(player, health)', category: 'Player', info: 'Sets the health of a player (clamped to max health).'},
  {label: 'api.player.getHealth', signature: 'api.player.getHealth(player)', category: 'Player', info: 'Returns the current health of a player.'},
  {label: 'api.player.getMaxHealth', signature: 'api.player.getMaxHealth(player)', category: 'Player', info: 'Returns the maximum health of a player.'},
  {label: 'api.player.damage', signature: 'api.player.damage(player, damage)', category: 'Player', info: 'Damages a player by a given amount.'},
  {label: 'api.player.setFoodLevel', signature: 'api.player.setFoodLevel(player, level)', category: 'Player', info: 'Sets the food level (0–20).'},
  {label: 'api.player.getFoodLevel', signature: 'api.player.getFoodLevel(player)', category: 'Player', info: 'Returns the food level (0–20).'},
  {label: 'api.player.setSaturation', signature: 'api.player.setSaturation(player, saturation)', category: 'Player', info: 'Sets the saturation value (how long food lasts).'},
  {label: 'api.player.getSaturation', signature: 'api.player.getSaturation(player)', category: 'Player', info: 'Returns the saturation value.'},
  {label: 'api.player.setLevel', signature: 'api.player.setLevel(player, level)', category: 'Player', info: 'Sets the experience level.'},
  {label: 'api.player.getLevel', signature: 'api.player.getLevel(player)', category: 'Player', info: 'Returns the experience level.'},
  {label: 'api.player.setExp', signature: 'api.player.setExp(player, exp)', category: 'Player', info: 'Sets the experience progress fraction (0.0–1.0).'},
  {label: 'api.player.getExp', signature: 'api.player.getExp(player)', category: 'Player', info: 'Returns the experience progress fraction.'},
  {label: 'api.player.giveExp', signature: 'api.player.giveExp(player, amount)', category: 'Player', info: 'Gives experience points.'},
  {label: 'api.player.hasPermission', signature: 'api.player.hasPermission(player, permission)', category: 'Player', info: 'Checks whether a player has a permission.'},
  {label: 'api.player.addPermission', signature: 'api.player.addPermission(player, permission)', category: 'Player', info: 'Temporarily grants a permission to a player.'},
  {label: 'api.player.removePermission', signature: 'api.player.removePermission(player, permission)', category: 'Player', info: 'Temporarily removes a permission from a player.'},
  {label: 'api.player.isOp', signature: 'api.player.isOp(player)', category: 'Player', info: 'Checks whether a player is an operator.'},
  {label: 'api.player.setOp', signature: 'api.player.setOp(player, op)', category: 'Player', info: 'Grants or removes operator status.'},
  {label: 'api.player.setMetaValue', signature: 'api.player.setPlayerMetadata(player, key, value)', category: 'Player', info: 'Stores an arbitrary value on a player.'},
  {label: 'api.player.getPlayerMetadata', signature: 'api.player.getPlayerMetadata(player, key)', category: 'Player', info: 'Reads a stored metadata value.'},
  {label: 'api.player.hasPlayerMetadata', signature: 'api.player.hasPlayerMetadata(player, key)', category: 'Player', info: 'Checks whether a player has a metadata key.'},
  {label: 'api.player.removePlayerMetadata', signature: 'api.player.removePlayerMetadata(player, key)', category: 'Player', info: 'Removes a metadata key from a player.'},
  {label: 'api.player.getPlayerPing', signature: 'api.player.getPlayerPing(player)', category: 'Player', info: 'Returns the ping of a player.'},

  {label: 'api.createItemStack', signature: 'api.createItemStack(material, [amount])', category: 'Items', info: 'Creates an item stack. material is a Material or a name string like "DIAMOND".'},
  {label: 'api.getMaterial', signature: 'api.getMaterial(name)', category: 'Items', info: 'Resolves a material by name ("DIAMOND", "STONE", …).'},
  {label: 'api.setItemDisplayName', signature: 'api.setItemDisplayName(item, name)', category: 'Items', info: 'Sets the display name of an item. Supports & color codes.'},
  {label: 'api.setItemLore', signature: 'api.setItemLore(item, lore)', category: 'Items', info: 'Sets the lore (tooltip lines) of an item. Accepts an array of lines.'},
  {label: 'api.giveItem', signature: 'api.giveItem(player, item)', category: 'Items', info: 'Gives an item stack to a player.'},
  {label: 'api.getItemInMainHand', signature: 'api.getItemInMainHand(player)', category: 'Items', info: 'Returns the item in the main hand of a player.'},
  {label: 'api.player.setItemInMainHand', signature: 'api.player.setItemInMainHand(player, item)', category: 'Items', info: 'Sets the item in the main hand of a player.'},
  {label: 'api.player.getItemInOffHand', signature: 'api.player.getItemInOffHand(player)', category: 'Items', info: 'Returns the item in the off hand of a player.'},
  {label: 'api.player.setItemInOffHand', signature: 'api.player.setItemInOffHand(player, item)', category: 'Items', info: 'Sets the item in the off hand of a player.'},
  {label: 'api.player.clearInventory', signature: 'api.player.clearInventory(player)', category: 'Items', info: 'Clears the entire inventory of a player.'},
  {label: 'api.item.addEnchantment', signature: 'api.item.addEnchantment(item, enchantment, level)', category: 'Items', info: 'Adds an enchantment, e.g. "SHARPNESS", "UNBREAKING".'},
  {label: 'api.item.removeEnchantment', signature: 'api.item.removeEnchantment(item, enchantment)', category: 'Items', info: 'Removes an enchantment.'},
  {label: 'api.item.hasEnchantment', signature: 'api.item.hasEnchantment(item, enchantment)', category: 'Items', info: 'Checks whether an item has an enchantment.'},

  {label: 'server.getWorld', signature: 'server.getWorld(name)', category: 'World', info: 'Returns the world with the given name or null.'},
  {label: 'server.getWorlds', signature: 'server.getWorlds()', category: 'World', info: 'Returns all loaded worlds.'},
  {label: 'api.world.setWorldTime', signature: 'api.world.setWorldTime(world, ticks)', category: 'World', info: 'Sets the time of day in ticks (0 day, 6000 noon, 12000 dusk, 18000 midnight).'},
  {label: 'api.world.getWorldTime', signature: 'api.world.getWorldTime(world)', category: 'World', info: 'Returns the current time of day in ticks.'},
  {label: 'api.world.setStorm', signature: 'api.world.setStorm(world, raining)', category: 'World', info: 'Starts or stops the rain.'},
  {label: 'api.world.isThundering', signature: 'api.world.isThundering(world)', category: 'World', info: 'Checks whether it is thundering.'},
  {label: 'api.world.setThundering', signature: 'api.world.setThundering(world, thundering)', category: 'World', info: 'Starts or stops thunder.'},
  {label: 'api.world.setWorldDifficulty', signature: 'api.world.setWorldDifficulty(world, "PEACEFUL|EASY|NORMAL|HARD")', category: 'World', info: 'Sets the world difficulty.'},
  {label: 'api.world.setWorldPVP', signature: 'api.world.setWorldPVP(world, pvp)', category: 'World', info: 'Enables or disables PvP in a world.'},
  {label: 'api.world.setWorldSpawnLocation', signature: 'api.world.setWorldSpawnLocation(world, location)', category: 'World', info: 'Sets the spawn point of a world.'},
  {label: 'api.world.getWorldSpawnLocation', signature: 'api.world.getWorldSpawnLocation(world)', category: 'World', info: 'Returns the spawn point of a world.'},
  {label: 'api.world.createExplosion', signature: 'api.world.createExplosion(location, power, [fire])', category: 'World', info: 'Creates an explosion at a location.'},
  {label: 'api.world.strikeLightning', signature: 'api.world.strikeLightning(location)', category: 'World', info: 'Strikes real lightning (with damage) at a location.'},
  {label: 'api.world.strikeLightningEffect', signature: 'api.world.strikeLightningEffect(location)', category: 'World', info: 'Strikes lightning without damage (effect only).'},
  {label: 'api.world.setWorldBorderSize', signature: 'api.world.setWorldBorderSize(world, size)', category: 'World', info: 'Sets the world border size.'},
  {label: 'api.world.isWorldAutoSave', signature: 'api.world.isWorldAutoSave(world)', category: 'World', info: 'Checks whether a world auto-saves.'},

  {label: 'api.block.setBlockType', signature: 'api.block.setBlockType(location, material)', category: 'Blocks', info: 'Sets the block type at a location.'},
  {label: 'api.block.getBlockType', signature: 'api.block.getBlockType(location)', category: 'Blocks', info: 'Returns the material at a location.'},
  {label: 'api.block.breakBlock', signature: 'api.block.breakBlock(location, [dropItems])', category: 'Blocks', info: 'Breaks the block at a location.'},
  {label: 'api.block.breakBlockNaturally', signature: 'api.block.breakBlockNaturally(block, [tool])', category: 'Blocks', info: 'Breaks a block as if mined by hand.'},
  {label: 'api.block.getBlock', signature: 'api.block.getBlock(location)', category: 'Blocks', info: 'Returns the Block object at a location.'},
  {label: 'api.block.getBlocksInRadius', signature: 'api.block.getBlocksInRadius(location, radius)', category: 'Blocks', info: 'Returns all blocks within a radius.'},

  {label: 'api.entity.spawnEntity', signature: 'api.entity.spawnEntity(location, entityType)', category: 'Entities', info: 'Spawns an entity. Type as string, e.g. "ZOMBIE", "COW", "VILLAGER".'},
  {label: 'api.entity.removeEntity', signature: 'api.entity.removeEntity(entity)', category: 'Entities', info: 'Removes an entity.'},
  {label: 'api.entity.setEntityCustomName', signature: 'api.entity.setEntityCustomName(entity, name)', category: 'Entities', info: 'Sets the display name of an entity.'},
  {label: 'api.entity.setEntityCustomNameVisible', signature: 'api.entity.setEntityCustomNameVisible(entity, visible)', category: 'Entities', info: 'Shows or hides the custom name tag.'},
  {label: 'api.entity.setEntityGlowing', signature: 'api.entity.setEntityGlowing(entity, glowing)', category: 'Entities', info: 'Makes an entity glow.'},
  {label: 'api.entity.setEntityGravity', signature: 'api.entity.setEntityGravity(entity, gravity)', category: 'Entities', info: 'Enables or disables gravity.'},
  {label: 'api.entity.setEntityInvulnerable', signature: 'api.entity.setEntityInvulnerable(entity, invulnerable)', category: 'Entities', info: 'Makes an entity invulnerable.'},
  {label: 'api.entity.setEntityAI', signature: 'api.entity.setEntityAI(entity, ai)', category: 'Entities', info: 'Enables or disables the AI of an entity.'},
  {label: 'api.entity.setEntitySilent', signature: 'api.entity.setEntitySilent(entity, silent)', category: 'Entities', info: 'Makes an entity silent.'},
  {label: 'api.entity.getNearbyEntities', signature: 'api.entity.getNearbyEntities(location, x, y, z)', category: 'Entities', info: 'Returns all entities within the given bounds.'},
  {label: 'api.entity.teleportEntity', signature: 'api.entity.teleportEntity(entity, location)', category: 'Entities', info: 'Teleports an entity to a location.'},
  {label: 'api.entity.setEntityVelocity', signature: 'api.entity.setEntityVelocity(entity, velocity)', category: 'Entities', info: 'Applies a velocity (new org.bukkit.util.Vector(x, y, z)).'},

  {label: 'api.playSound', signature: 'api.playSound(player|location, sound, volume, pitch)', category: 'Sound', info: 'Plays a sound. Sound names like "ENTITY_PLAYER_LEVELUP", "BLOCK_ANVIL_USE".'},
  {label: 'api.spawnParticle', signature: 'api.spawnParticle(location, particle, count, [offsetX, offsetY, offsetZ, extra])', category: 'Sound', info: 'Spawns particles. Names like "FLAME", "HEART", "VILLAGER_HAPPY".'},

  {label: 'api.runTaskLater', signature: 'api.runTaskLater(delaySeconds, fn)', category: 'Scheduling', info: 'Runs a function once after a delay in seconds.'},
  {label: 'api.runTaskTimer', signature: 'api.runTaskTimer(delaySeconds, periodSeconds, fn)', category: 'Scheduling', info: 'Repeats a function every period seconds.'},
  {label: 'api.runTask', signature: 'api.runTask(fn)', category: 'Scheduling', info: 'Runs a function on the main thread on the next tick.'},
  {label: 'api.runTaskAsync', signature: 'api.runTaskAsync(fn)', category: 'Scheduling', info: 'Runs a function asynchronously (off the main thread).'},
  {label: 'api.runTaskLaterAsync', signature: 'api.runTaskLaterAsync(delaySeconds, fn)', category: 'Scheduling', info: 'Runs a function asynchronously after a delay.'},
  {label: 'api.cancelTask', signature: 'api.cancelTask(task)', category: 'Scheduling', info: 'Cancels a scheduled task (keep the return value of runTaskLater/Timer).'},

  {label: 'api.createGUI', signature: 'api.createGUI(title, rows)', category: 'GUI', info: 'Creates a GUI builder. Chain .setItem(slot, item), .onClick(fn), .build(), .open(player).'},
  {label: 'api.inventory.createCustomInventory', signature: 'api.inventory.createCustomInventory(size, title)', category: 'GUI', info: 'Creates a custom inventory (size multiple of 9).'},
  {label: 'api.inventory.createInventoryHolder', signature: 'api.inventory.createInventoryHolder()', category: 'GUI', info: 'Creates a holder that tracks data and close state.'},
  {label: 'api.inventory.setInventoryItem', signature: 'api.inventory.setInventoryItem(inventory, slot, item)', category: 'GUI', info: 'Places an item in a slot.'},
  {label: 'api.inventory.getInventoryItem', signature: 'api.inventory.getInventoryItem(inventory, slot)', category: 'GUI', info: 'Returns the item in a slot.'},
  {label: 'api.inventory.addItemToInventory', signature: 'api.inventory.addItemToInventory(inventory, item)', category: 'GUI', info: 'Adds an item, returns false if the inventory is full.'},
  {label: 'api.inventory.removeItemFromInventory', signature: 'api.inventory.removeItemFromInventory(inventory, item)', category: 'GUI', info: 'Removes an item, returns false if it was not fully found.'},
  {label: 'api.inventory.inventoryContains', signature: 'api.inventory.inventoryContains(inventory, item)', category: 'GUI', info: 'Checks whether an inventory contains an item.'},
  {label: 'api.inventory.clearInventory', signature: 'api.inventory.clearInventory(inventory)', category: 'GUI', info: 'Clears an inventory.'},
  {label: 'api.inventory.updateInventoryItem', signature: 'api.inventory.updateInventoryItem(inventory, slot, item)', category: 'GUI', info: 'Updates an item in a live inventory.'},
  {label: 'api.inventory.refreshInventory', signature: 'api.inventory.refreshInventory(inventory)', category: 'GUI', info: 'Re-renders a custom GUI from its stored items.'},
  {label: 'api.inventory.getFirstEmptySlot', signature: 'api.inventory.getFirstEmptySlot(inventory)', category: 'GUI', info: 'Returns the first empty slot or -1.'},

  {label: 'api.getPluginConfigValue', signature: 'api.getPluginConfigValue(pluginId, key, [fallback])', category: 'Storage', info: 'Reads a value from the YAML config storage.'},
  {label: 'api.setPluginConfigValue', signature: 'api.setPluginConfigValue(pluginId, key, value)', category: 'Storage', info: 'Writes a value to the YAML config storage.'},
  {label: 'api.saveYamlFile', signature: 'api.saveYamlFile(fileName, data)', category: 'Storage', info: 'Saves a map as a YAML file in the plugin data folder.'},
  {label: 'api.loadYamlFile', signature: 'api.loadYamlFile(fileName)', category: 'Storage', info: 'Loads a YAML file as a map.'},
  {label: 'api.saveJsonFile', signature: 'api.saveJsonFile(fileName, jsonString)', category: 'Storage', info: 'Saves a JSON string to a file.'},
  {label: 'api.loadJsonFile', signature: 'api.loadJsonFile(fileName)', category: 'Storage', info: 'Loads a JSON file as a string.'},
  {label: 'api.file.saveTextFile', signature: 'api.file.saveTextFile(fileName, content)', category: 'Storage', info: 'Saves plain text to a file.'},
  {label: 'api.file.loadTextFile', signature: 'api.file.loadTextFile(fileName)', category: 'Storage', info: 'Loads a plain text file.'},
  {label: 'api.pluginFileExists', signature: 'api.pluginFileExists(fileName)', category: 'Storage', info: 'Checks whether a plugin data file exists.'},

  {label: 'api.createTable', signature: 'api.createTable(dbName, tableName, columns)', category: 'Database', info: 'Creates a table. columns: {name: "TEXT", points: "INTEGER"}. Persistent across restarts.'},
  {label: 'api.insertData', signature: 'api.insertData(dbName, tableName, data)', category: 'Database', info: 'Inserts a row. data: {name: "Alex", points: 10}.'},
  {label: 'api.insertDataAndGetId', signature: 'api.insertDataAndGetId(dbName, tableName, data)', category: 'Database', info: 'Inserts a row and returns the generated ID.'},
  {label: 'api.querySQL', signature: 'api.querySQL(dbName, sql)', category: 'Database', info: 'Runs a SELECT query, returns an array of row maps.'},
  {label: 'api.executeSQL', signature: 'api.executeSQL(dbName, sql)', category: 'Database', info: 'Runs UPDATE/DELETE/INSERT SQL.'},
  {label: 'api.database.updateData', signature: 'api.database.updateData(dbName, tableName, data, whereClause)', category: 'Database', info: 'Updates rows matching a WHERE clause.'},
  {label: 'api.database.deleteData', signature: 'api.database.deleteData(dbName, tableName, whereClause)', category: 'Database', info: 'Deletes rows matching a WHERE clause.'},
  {label: 'api.database.countRows', signature: 'api.database.countRows(dbName, tableName, [whereClause])', category: 'Database', info: 'Counts rows in a table.'},

  {label: 'api.utility.randomInt', signature: 'api.utility.randomInt(min, max)', category: 'Utility', info: 'Random integer between min and max (inclusive).'},
  {label: 'api.utility.randomDouble', signature: 'api.utility.randomDouble(min, max)', category: 'Utility', info: 'Random double between min and max.'},
  {label: 'api.utility.randomBoolean', signature: 'api.utility.randomBoolean()', category: 'Utility', info: 'Random true/false.'},
  {label: 'api.utility.colorize', signature: 'api.utility.colorize(text)', category: 'Utility', info: 'Converts & color codes to colored text.'},
  {label: 'api.utility.stripColor', signature: 'api.utility.stripColor(text)', category: 'Utility', info: 'Removes all color codes.'},
  {label: 'api.utility.formatDate', signature: 'api.utility.formatDate(timestamp, [pattern])', category: 'Utility', info: 'Formats a timestamp as a readable date.'},
  {label: 'api.utility.executeCommand', signature: 'api.utility.executeCommand(command)', category: 'Utility', info: 'Executes a console command, e.g. "give Alex diamond 1".'},
  {label: 'api.utility.round', signature: 'api.utility.round(value, places)', category: 'Utility', info: 'Rounds a number to decimal places.'},
  {label: 'api.utility.clamp', signature: 'api.utility.clamp(value, min, max)', category: 'Utility', info: 'Clamps a number between min and max.'},
  {label: 'api.utility.isPlayer', signature: 'api.utility.isPlayer(sender)', category: 'Utility', info: 'Checks whether a command sender is a player (not console).'},
  {label: 'api.utility.executeCommand', signature: 'api.utility.executeCommand(cmd)', category: 'Utility', info: 'Runs a server console command.'},
  {label: 'api.getCurrentTimeMillis', signature: 'api.getCurrentTimeMillis()', category: 'Utility', info: 'Current time in milliseconds since the epoch.'},
  {label: 'api.md5', signature: 'api.md5(input)', category: 'Utility', info: 'MD5 hash of a string.'},
  {label: 'api.sha256', signature: 'api.sha256(input)', category: 'Utility', info: 'SHA-256 hash of a string.'},
  {label: 'api.base64Encode', signature: 'api.base64Encode(input)', category: 'Utility', info: 'Base64-encodes a string.'},
  {label: 'api.base64Decode', signature: 'api.base64Decode(input)', category: 'Utility', info: 'Base64-decodes a string.'},
  {label: 'api.getServerVersion', signature: 'api.getServerVersion()', category: 'Utility', info: 'Returns the server software version.'},
  {label: 'api.getMaxPlayers', signature: 'api.getMaxPlayers()', category: 'Utility', info: 'Returns the configured player limit.'},

  {label: 'api.network.httpGet', signature: 'api.network.httpGet(url)', category: 'Network', info: 'Performs a GET request and returns the response body.'},
  {label: 'api.network.httpPost', signature: 'api.network.httpPost(url, data)', category: 'Network', info: 'Performs a POST request with a body string.'},

  {label: 'api.vault.isAvailable', signature: 'api.vault.isAvailable()', category: 'Vault', info: 'Checks whether a Vault economy provider is present.'},
  {label: 'api.vault.balance', signature: 'api.vault.balance(player)', category: 'Vault', info: 'Returns the balance of a player.'},
  {label: 'api.vault.has', signature: 'api.vault.has(player, amount)', category: 'Vault', info: 'Checks whether the player has at least the given amount.'},
  {label: 'api.vault.deposit', signature: 'api.vault.deposit(player, amount)', category: 'Vault', info: 'Adds money. Returns a Result with isSuccess(), getError(), getBalance().'},
  {label: 'api.vault.withdraw', signature: 'api.vault.withdraw(player, amount)', category: 'Vault', info: 'Removes money. Returns a Result with isSuccess(), getError(), getBalance().'},
  {label: 'api.vault.transfer', signature: 'api.vault.transfer(from, to, amount)', category: 'Vault', info: 'Transfers money between two players. Returns a Result.'},
  {label: 'api.vault.purchase', signature: 'api.vault.purchase(player, cost, item)', category: 'Vault', info: 'Buys an item with balance check and stock deduction. Returns a Result.'},
  {label: 'api.vault.format', signature: 'api.vault.format(amount)', category: 'Vault', info: 'Formats money using the provider currency symbol.'},
  {label: 'api.vault.getProviderName', signature: 'api.vault.getProviderName()', category: 'Vault', info: 'Name of the active economy provider, or "Unavailable".'},
  {label: 'api.vault.getPrimaryGroup', signature: 'api.vault.getPrimaryGroup(player)', category: 'Vault', info: 'Primary permission group of a player.'},
  {label: 'api.vault.getPrefix', signature: 'api.vault.getPrefix(player)', category: 'Vault', info: 'Chat prefix of a player group.'},

  {label: 'api.registerCommand', signature: 'api.registerCommand(name, fn)', category: 'Commands', info: 'Registers a custom command. fn receives (sender, args). Return true to mark it handled.'},
  {label: 'api.registerCommandDescripted', signature: 'api.registerCommand(name, description, usage, fn)', category: 'Commands', info: 'Registers a command with description and usage.'},
  {label: 'api.registerCommandTab', signature: 'api.registerCommand(name, description, usage, fn, tabCompleter)', category: 'Commands', info: 'Registers a command with a tab-completer function (sender, args) => string[].'},
  {label: 'sender', signature: 'sender', category: 'Commands', info: 'The command executor (player or console) inside a command handler.'},
  {label: 'sender.name', signature: 'sender.name', category: 'Commands', info: 'Player name of the command sender.'},
  {label: 'args', signature: 'args', category: 'Commands', info: 'Command arguments as an array of strings inside a command handler.'},
  {label: 'args.length', signature: 'args.length', category: 'Commands', info: 'Number of command arguments.'},

  {label: 'event.getPlayer', signature: 'event.getPlayer()', category: 'Events', info: 'Returns the player who triggered the event (player/block/inventory events).'},
  {label: 'event.getEntity', signature: 'event.getEntity()', category: 'Events', info: 'Returns the entity involved in an entity event.'},
  {label: 'event.getBlock', signature: 'event.getBlock()', category: 'Events', info: 'Returns the block involved in a block event.'},
  {label: 'event.getTo', signature: 'event.getTo()', category: 'Events', info: 'Destination of a movement event.'},
  {label: 'event.getFrom', signature: 'event.getFrom()', category: 'Events', info: 'Origin of a movement event.'},
  {label: 'event.getAction', signature: 'event.getAction()', category: 'Events', info: 'The click action of an interaction event.'},
  {label: 'event.getSlot', signature: 'event.getSlot()', category: 'Events', info: 'Slot number of an inventory click.'},
  {label: 'event.getCurrentItem', signature: 'event.getCurrentItem()', category: 'Events', info: 'The item currently in a clicked slot.'},
  {label: 'event.getMessage', signature: 'event.getMessage()', category: 'Events', info: 'The chat message of a chat event.'},
  {label: 'event.setCancelled', signature: 'event.setCancelled(bool)', category: 'Events', info: 'Cancels an event (prevents its default behaviour).'},

  {label: 'api.scoreboard.createScoreboard', signature: 'api.scoreboard.createScoreboard()', category: 'Scoreboard', info: 'Creates a new scoreboard.'},
  {label: 'api.scoreboard.createObjective', signature: 'api.scoreboard.createObjective(scoreboard, name, criteria, displayName)', category: 'Scoreboard', info: 'Registers an objective and shows it on the sidebar.'},
  {label: 'api.scoreboard.getObjective', signature: 'api.scoreboard.getObjective(scoreboard, name)', category: 'Scoreboard', info: 'Returns an existing objective.'},
  {label: 'api.scoreboard.createTeam', signature: 'api.scoreboard.createTeam(scoreboard, name)', category: 'Scoreboard', info: 'Creates a team.'},
  {label: 'api.scoreboard.getTeam', signature: 'api.scoreboard.getTeam(scoreboard, name)', category: 'Scoreboard', info: 'Returns an existing team.'},
  {label: 'objective.getScore', signature: 'objective.getScore(playerName).setScore(n)', category: 'Scoreboard', info: 'Sets a score line on a sidebar objective.'},
];

export function categories() {
  const order = ['Lifecycle', 'Systems', 'Globals', 'Events', 'Commands', 'Messages', 'Player', 'Items', 'World', 'Blocks',
    'Entities', 'Sound', 'Scheduling', 'GUI', 'Storage', 'Database', 'Utility', 'Network', 'Vault', 'Scoreboard'];
  const groups = {};
  for (const entry of apiDocs) {
    (groups[entry.category] ||= []).push(entry);
  }
  return Object.keys(groups)
    .sort((a, b) => order.indexOf(a) - order.indexOf(b) || a.localeCompare(b))
    .map(name => ({name, entries: groups[name]}));
}
